apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins
  labels:
    jenkins-label: POD_LABEL
spec:
  hostAliases:
  - ip: "10.3.1.10"
    hostnames:
    - "s3.ubuntu.home"
  initContainers:
  - name: jnlp-init
    command:
    - /bin/bash
    - -c
    - |
      set -x
      cd /usr/local/share/ca-certificates/
      update-ca-certificates -f
      cd /tmp/certs
      cp -rL /etc/ssl/certs/* .
      chmod 644 *
      cd /var/run/keystore
      keytool -importcert -cacerts -noprompt -trustcacerts -alias jenkins_root -file /usr/local/share/ca-certificates/root.crt -storepass changeit
      keytool -importcert -cacerts -noprompt -trustcacerts -alias jenkins_server -file /usr/local/share/ca-certificates/server.crt -storepass changeit
      cp -rL "${JAVA_HOME}/lib/security/cacerts" .
      chmod 644 *
    image: s2.ubuntu.home:5000/docker.io/jenkins/inbound-agent:4.13.3-1-jdk17
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    securityContext:
        runAsUser: 0
    tty: true
    volumeMounts:
    - name: root-certs
      mountPath: /usr/local/share/ca-certificates/root.crt
      readOnly: false
      subPath: tls.crt
    - name: root-certs
      mountPath: /usr/local/share/ca-certificates/root.key
      readOnly: false
      subPath: tls.key
    - name: server-certs
      mountPath: /usr/local/share/ca-certificates/server.crt
      readOnly: false
      subPath: tls.crt
    - name: server-certs
      mountPath: /usr/local/share/ca-certificates/server.key
      readOnly: false
      subPath: tls.key
    - name: certs-volume
      mountPath: /tmp/certs
    - name: keystore-volume
      mountPath: /var/run/keystore
  containers:
  - name: jnlp
    image: s2.ubuntu.home:5000/docker.io/jenkins/inbound-agent:4.13.3-1-jdk17
#    env:
      # running under Java 11 gives "illegal reflective access" warnings
      # https://github.com/glencoesoftware/raw2ometiff/issues/18
#      - name: JAVA_OPTS
#        value: '--add-opens=java.base/java.lang.reflect=ALL-UNNAMED'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    securityContext:
        runAsUser: 1000
    stdin: true
    tty: true
    volumeMounts:
    - name: certs-volume
      mountPath: /etc/ssl/certs
    - name: keystore-volume
      mountPath: /opt/java/openjdk/lib/security/cacerts
      readOnly: true
      subPath: cacerts
    - name: workspace-volume
      mountPath: /home
  - name: postgres
    image: s2.ubuntu.home:5000/docker.io/postgres:16.1-alpine3.18
    imagePullPolicy: IfNotPresent
    ports:
      - name: postgres
        containerPort: 5432
        protocol: TCP
    env:
      - name: POSTGRES_DB
        value: postgres
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: admin123
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: postgredb
      - mountPath: /home
        name: sharedvolume
  - name: python
    args:
    - cat
    tty: true
    image: s2.ubuntu.home:5000/docker.io/python:3.9.18
    imagePullPolicy: IfNotPresent
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /home
        name: sharedvolume
  - name: build-container
    args:
    - cat
    tty: true
    image: s2.ubuntu.home:5000/alpine/build_container:dev
    imagePullPolicy: IfNotPresent
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /home
        name: sharedvolume
  restartPolicy: Never
#  ttlSecondsAfterFinished: 120
  volumes:
  - name: root-certs
    secret:
      secretName: root-ca
      defaultMode: 0400
      items:
      - key: tls.key
        path: tls.key
      - key: tls.crt
        path: tls.crt
  - name: server-certs
    secret:
      secretName: server-ca
      defaultMode: 0400
      items:
      - key: tls.key
        path: tls.key
      - key: tls.crt
        path: tls.crt
  - name: certs-volume
    emptyDir: {}
  - name: keystore-volume
    emptyDir: {}
  - name: workspace-volume
    emptyDir: {}
  - name: postgredb
    emptyDir: {}
  - name: sharedvolume
    emptyDir: {}
